<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-4 col-md-3 control-label">
        <label for="{{ formData.id }}" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
            <i class="fa fa-question-circle-o text-muted" ng-if="formData.description != null"></i>
            {{ formData.label }}
            <span ng-if="formData.required">*</span>
        </label>
        <span class="fa fa-fw text-danger pull-left"
              ng-class="{'fa-exclamation-triangle': formData.errors.length}"></span>
    </div>
    <!--    <div ng-class="{'col-sm-8': formData.value.id == null, 'col-md-9': formData.value.id == null, 'col-sm-6': formData.value.id > 0, 'col-md-7': formData.value.id > 0}">-->
    <div class="col-sm-8 col-md-9 col-control">
        <div class="control-actions">
            <button type="button" class="btn btn-link" ng-show="formData.value.id > 0 && !formData.readonly" ng-click="empty()">
                <i class="fa fa-fw fa-times"></i>
            </button>
        </div>

        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value.id }}">
        <div class="input-group">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="selectMedia()"
                   uib-popover="<?= $this->translate('button.select', 'admin') ?>" popover-trigger="'mouseenter'">
                    <i class="fa fa-fw fa-picture-o text-info"></i>
                </button>
            </span>
            <input type="text" class="form-control" style="padding-right:36px;" value="{{ formData.value.filename }}"
                   disabled>
        </div>

        <div ng-show="formData.value.id > 0">
            <div class="item">
                <div class="pos-rlt bg-for-transparent">
                    <div class="top w-full m-l-sm">
                        <a ng-show="isImage(formData.value)" class="m-t-sm btn btn-rounded btn-icon btn-default"
                           ng-href="{{ getSrc(formData.value) }}" lightbox>
                            <i class="fa fa-search-plus"></i>
                        </a>
                        <a class="m-t-sm btn btn-rounded btn-icon btn-default"
                           ng-href="<?= $this->url('admin/media/edit', ['id' => '{{formData.value.id}}']) ?>"
                           target="_blank">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="m-t-sm btn btn-rounded btn-icon btn-default"
                           ng-href="{{ getSrc(formData.value) }}" target="_blank">
                            <i class="fa fa-share"></i>
                        </a>
                    </div>
                    <div class="text-center" style="overflow: hidden; height: 100px;">
                        <div ng-show="!isImage(formData.value)" class="center text-center m-t-n w-full r-2x">
                            <i class="fa fa-5x" ng-class="getDocumentClass(formData.value)"></i>
                        </div>
                        <img ng-show="isImage(formData.value)" ng-src="{{ getSrc(formData.value, 'admin_thumbnail') }}"
                             class="r r-2x" style="display:inline-block;max-width:100%;max-height:100%">
                        <img ng-show="!isImage(formData.value)"
                             src="<?= $this->assetUrl('/images/document-placeholder.jpg', 'admin42') ?>"
                             class="r r-2x" style="display:inline-block;max-width:100%;max-height:100%">
                    </div>
                </div>
            </div>
        </div>

        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
