<div class="form-group" ng-class="{'has-error': formData.errors.length}">
    <div class="col-sm-3 col-md-2 control-label">
        <div class="pull-left hidden-sm hidden-xs">
            <span class="fa fa-fw text-danger" ng-class="{'fa-exclamation-triangle': formData.errors.length}"></span>
            <a ng-show="formData.value.id > 0" class="text-light" ng-click="empty()">
                <i class="fa fa-fw fa-trash"></i>
            </a>
        </div>
        <div class="pull-right">
            <a class="text-muted" ng-if="formData.description != null" uib-popover="{{ formData.description }}" popover-trigger="'mouseenter'">
                <i class="fa fa-question-circle"></i>
            </a>
            <label for="{{ formData.id }}">{{ formData.label }}</label>
            <span ng-if="formData.required">*</span>
        </div>
        <div class="clearfix"></div>
    </div>
    <div ng-show="formData.value.id > 0" class="col-sm-2 col-md-2">
        <div class="item" style="overflow: hidden;">
            <div class="pos-rlt bg-for-transparent">
                <div class="top w-full m-l-sm">
                    <a ng-show="isImage(formData.value)" class="m-t-sm btn btn-rounded btn-icon btn-default" ng-href="{{ getSrc(formData.value) }}" lightbox>
                        <i class="fa fa-search-plus"></i>
                    </a>
                    <a class="m-t-sm btn btn-rounded btn-icon btn-default" ng-href="<?= $this->url('admin/media/edit', ['id' => '{{formData.value.id}}'])?>" target="_blank">
                        <i class="fa fa-edit"></i>
                    </a>
                </div>
                <div ng-show="!isImage(formData.value)" class="center text-center m-t-n w-full r-2x">
                    <i class="fa fa-5x" ng-class="getDocumentClass(formData.value)"></i>
                </div>

                <img ng-show="isImage(formData.value)" ng-src="{{ getSrc(formData.value, 'admin_thumbnail') }}" class="img-full r r-2x">
                <img ng-show="!isImage(formData.value)" src="<?= $this->assetUrl('/images/document-placeholder.jpg', 'admin42') ?>" class="img-full r r-2x">
            </div>
        </div>
    </div>
    <div ng-class="{'col-sm-9': formData.value.id == null, 'col-md-10': formData.value.id == null, 'col-sm-7': formData.value.id > 0, 'col-md-8': formData.value.id > 0}">
        <input type="hidden" name="{{ formData.name }}" value="{{ formData.value.id }}">
        <div class="input-group">
            <input type="text" class="form-control" value="{{ formData.value.filename }}" disabled>
            <span class="input-group-btn">
                <a type="button" class="btn btn-default" ng-click="selectMedia()">
                    <i class="fa fa-check"></i>
                    <?= $this->translate('button.select', 'admin') ?>
                </a>
            </span>
        </div>

        <ul ng-if="formData.errors.length" class="list-unstyled text-danger">
            <li ng-repeat="message in formData.errors">{{ message }}</li>
        </ul>
    </div>
</div>
