<div class="modal-header">
    <h3 class="modal-title"><?= $this->translate('title.media', 'admin') ?></h3>
</div>
<div class="modal-body modal-scroll-body">
    <div class="container-fluid">
        <ng-include src="mediaUrl"></ng-include>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">
        <span class="fa fa-check"></span>
        <?= $this->translate('button.select', 'admin') ?>
    </button>
    <button class="btn btn-default" ng-click="cancel()">
        <?= $this->translate('button.cancel', 'admin') ?>
    </button>
</div>
